import React from 'react';

import { Menu } from '@src/components/MenuSide/types';

export const sidebarConfig: Menu[] = [
	{
		name: 'Página inicial',
		icon: <i className="fa-regular fa-house" />,
		link: 'home',
		bold: true,
		subMenu: [],
		role: null,
		disabled: true,
		default: true,
	},
	{
		name: 'Contatos',
		icon: <i className="fa-regular fa-address-card" />,
		link: '',
		bold: false,
		role: null,
		disabled: false,
		default: true,
		subMenu: [
			{
				name: 'Base de contatos',
				link: 'vuc',
				bold: false,
				role: null,
				disabled: true,
				default: true,
			},
			{
				name: 'Segmentar contatos',
				link: 'configuration/rules-engine',
				bold: false,
				role: null,
				disabled: false,
				default: true,
			},
			{
				name: 'Importar contatos',
				link: 'configuration/contact-list',
				bold: false,
				role: null,
				disabled: false,
				default: true,
			},
		],
	},
	{
		name: 'Automações',
		icon: <i className="fa-regular fa-code-branch" />,
		link: 'journey',
		bold: false,
		subMenu: [],
		role: null,
		disabled: true,
		default: true,
	},
	{
		name: 'Documentos',
		icon: <i className="fa-regular fa-file-lines" />,
		link: 'documents',
		bold: false,
		subMenu: [],
		role: null,
		disabled: true,
		default: true,
	},
	{
		name: 'Análises',
		icon: <i className="fak fa-chart-circular-medium" />,
		link: '',
		bold: false,
		role: null,
		disabled: false,
		default: true,
		subMenu: [
			{
				name: 'Visão geral',
				link: 'analysis',
				bold: false,
				role: null,
				disabled: true,
				default: true,
			},
			{
				name: 'Personalizado',
				link: 'customizable-report',
				bold: false,
				role: null,
				disabled: true,
				default: true,
			},
			{
				name: 'Exportar relatório',
				link: 'configuration/export-data',
				bold: false,
				role: null,
				disabled: false,
				default: true,
			},
		],
	},
];
